apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

android {
    namespace 'com.yalantis.ucrop'
    compileSdk 34
    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 34
        versionCode 27
        versionName "2.2.9-native"

        vectorDrawables.useSupportLibrary = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    lintOptions {
        abortOnError false
    }

    resourcePrefix 'ucrop_'

    sourceSets.main {
        jni.srcDirs = []
    }

    publishing {
        singleVariant("release") {
            // sourcesJar, javadocJar 등 추가하고 싶으면 활성화
            withSourcesJar()
            // withJavadocJar()
        }
    }

    buildFeatures {
        buildConfig true
    }

}
afterEvaluate {
    publishing {
        publications {
            // 보통 Android 라이브러리는 'release' 컴포넌트를 사용합니다.
            release(MavenPublication) {
                groupId    = project.group
                artifactId = project.name
                version    = project.version
                from components.release
            }
        }
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:${androidx_appcompat_version}"
    implementation "androidx.exifinterface:exifinterface:${androidx_exifinterface_version}"
    implementation "androidx.transition:transition:${androidx_transition_version}"
    // OkHttp3 versions above 3.12.x don't support pre-Lollipop Android versions (API 21)
    implementation "com.squareup.okhttp3:okhttp:3.12.13"
    implementation "androidx.activity:activity-ktx:1.8.2"
    implementation "androidx.core:core-ktx:1.12.0"
}
